### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [floostack/transcoder#2]
I found that this project already [supports Go modules](https://github.com/floostack/transcoder/blob/master/go.mod). But sadly, the [tags](https://github.com/floostack/transcoder/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/floostack/transcoder v0.0.0-20200804154457-1f7b65086680
```
Else the mod file shows something like `github.com/floostack/transcoder v0.0.0-20200804154457-1f7b65086680` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@xfrr  Could you help me review this issue? Thx :p

**Comment by xfrr** [comment]
Sure, I've modified 1.0.0 to v1.1.0, we'll keep it that way.
Thanks for your contribution.

**Comment by KateGo520** [comment]
@xfrr Thank you for your contribution!
